FROM rust:1.80.1 as builder

WORKDIR /app

COPY . .

RUN rustup target add aarch64-unknown-linux-musl
RUN cargo build --release --target=aarch64-unknown-linux-musl

FROM scratch

COPY --from=builder /app/target/aarch64-unknown-linux-musl/release/rust /rust

CMD ["/rust"]
